openapi: 3.0.0
info:
  title: Notum Docs
  version: 1.0.0
servers:
  - url: http://localhost:4000
tags:
  - name: Auth
    description: Authentication / Authorization
  - name: Courses
    description: Add, edit, delete courses in the database
  - name: Lessons
    description: Add, edit, delete lessons in the database
paths:
  /api/auth/signup:
    post:
      tags:
        - Auth
      description: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - name
                - password
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
        required: true
      responses:
        201:
          description: User successfully created
          content:
            application/json:
              schema:
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
  /api/auth/login:
    post:
      tags:
        - Auth
      description: Logs a user in
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
  /api/auth/logout:
    post:
      tags:
        - Auth
      description: Logs a user out and removed the session cookie
      responses:
        200:
          description: Logout successful
          content:
            application/json:
              schema:
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /api/auth/check:
    get:
      tags:
        - Auth
      description: For quick checking if the user is logged in or not
      responses:
        200:
          description: Returns an object with isLogged and id (optional).
          content:
            application/json:
              schema:
                required:
                  - isLoggedIn
                properties:
                  isLoggedIn:
                    type: boolean
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
  /api/courses:
    post:
      tags:
        - Courses
      description: Add a course to the database.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - start_date
                - color
              properties:
                name:
                  type: string
                start_date:
                  type: number
                end_date:
                  type: number
                color:
                  type: string
                weekly_schedule:
                  properties:
                    monday:
                      type: array
                      items:
                        properties:
                          start_date:
                            type: string
                          end_date:
                            type: string
                    tuesday:
                      type: array
                      items:
                        properties:
                          start_date:
                            type: string
                          end_date:
                            type: string
                    wednesday:
                      type: array
                      items:
                        properties:
                          start_date:
                            type: string
                          end_dat:
                            type: string
                    thursday:
                      type: array
                      items:
                        properties:
                          start_date:
                            type: string
                          end_date:
                            type: string
                    friday:
                      type: array
                      items:
                        properties:
                          start_date:
                            type: string
                          end_date:
                            type: string
        required: true

      responses:
        201:
          description: Returns the new course once successfully created.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      _id:
                        type: string
                      __v:
                        type: string
                      name:
                        type: string
                      start_date:
                        type: number
                      end_date:
                        type: number
                      color:
                        type: string
                      weekly_schedule:
                        properties:
                          monday:
                            type: array
                            items:
                              properties:
                                start_date:
                                  type: string
                                end_date:
                                  type: string
                          tuesday:
                            type: array
                            items:
                              properties:
                                start_date:
                                  type: string
                                end_date:
                                  type: string
                          wednesday:
                            type: array
                            items:
                              properties:
                                start_date:
                                  type: string
                                end_dat:
                                  type: string
                          thursday:
                            type: array
                            items:
                              properties:
                                start_date:
                                  type: string
                                end_date:
                                  type: string
                          friday:
                            type: array
                            items:
                              properties:
                                start_date:
                                  type: string
                                end_date:
                                  type: string
  /api/courses/weekly-schedule:
    get:
      tags:
        - Courses
      description: Get weekly-schedule.
      parameters:
        - in: query
          name: weekId
          schema:
            type: integer
          description: (optional) weekId to get the weekly-schedule of the specific week
      responses:
        200:
          description: Returns the weekly schedule.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      week_id:
                        type: number
                      start_date:
                        type: number
                      end_date:
                        type: number
                      prev_week_id:
                        type: number
                      next_week_id:
                        type: number
                      schedules:
                        type: array
                        items:
                          properties:
                            day:
                              type: string
                            date:
                              type: number
                            lessons:
                              type: array
                              items:
                                properties:
                                  _id:
                                    type: string
                                  name:
                                    type: string
                                  color:
                                    type: string
                                  start_time:
                                    type: string
                                  end_time:
                                    type: string
  /api/lessons:
    get:
      tags:
        - Lessons
      description: Get all lessons of the user.
      responses:
        200:
          description: Returns all the lessons of the user.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      properties:
                        _id:
                          type: string
                        course_id:
                          type: string
                        schedule_id:
                          type: string
                        course_name:
                          type: string
                        start_time:
                          type: string
                        end_time:
                          type: string
                        color:
                          type: string
                        unit:
                          type: string
                        tags:
                          type: array
                          item:
                            type: string
                        note:
                          type: string
                        date:
                          type: number
                        attachments:
                          type: array
                          items:
                            type: string
    post:
      tags:
        - Lessons
      description: POST lesson.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - date
                - schedule_id
                - course_id
              properties:
                unit:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                note:
                  type: string
                date:
                  type: number
                attachments:
                  type: array
                  items:
                    type: string
                schedule_id:
                  type: string
                course_id:
                  type: string
        required: true
      responses:
        200:
          description: Returns the new lesson created.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      _id:
                        type: string
                      unit:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
                      date:
                        type: number
                      attachments:
                        type: array
                        items:
                          type: string
                      schedule_id:
                        type: string
                      course_id:
                        type: string
  /api/lessons/{lessonId}:
    get:
      tags:
        - Lessons
      description: Get lesson by id.
      parameters:
        - in: path
          name: lessonId
          schema:
            type: string
          required: true
          description: lessonId
      responses:
        200:
          description: Returns the lesson.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      _id:
                        type: string
                      course_id:
                        type: string
                      schedule_id:
                        type: string
                      course_name:
                        type: string
                      start_time:
                        type: string
                      end_time:
                        type: string
                      color:
                        type: string
                      unit:
                        type: string
                      tags:
                        type: array
                        item:
                          type: string
                      note:
                        type: string
                      date:
                        type: number
                      attachments:
                        type: array
                        items:
                          type: string
    put:
      tags:
        - Lessons
      description: Update lesson.
      parameters:
        - in: path
          name: lessonId
          schema:
            type: string
          required: true
          description: lessonId
      requestBody:
        content:
          application/json:
            schema:
              properties:
                unit:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                note:
                  type: string
                attachments:
                  type: array
                  items:
                    type: string
        required: true
      responses:
        201:
          description: Returns the updated lesson.
          content:
            application/json:
              schema:
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      _id:
                        type: string
                      unit:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
                      date:
                        type: number
                      attachments:
                        type: array
                        items:
                          type: string
                      schedule_id:
                        type: string
                      course_id:
                        type: string
    delete:
      tags:
        - Lessons
      description: Delete lesson.
      parameters:
        - in: path
          name: lessonId
          schema:
            type: string
          required: true
          description: lessonId
      responses:
        201:
          content:
            application/json:
              schema:
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                