name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set client/** as root
        run: git subtree split --prefix client main
      
      - name: npm install
        run: npm install
      
      - name: Git  add and commit
        run: |
          git add -A
          git commit -m "by github-actions"

      - name: Add frontend remote origin
        run: git remote add lesson-plans-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME  }}.git
      
      - name: Deploy frontend to Heroku
        run: git push lesson-plans-frontend
