name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Add frontend remote origin
        run: git remote add lesson-plans-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME  }}.git
      
      - name: Deploy frontend to Heroku
        run: git push lesson-plans-frontend `git subtree split --prefix client main`:refs/heads/main --force
