name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set client/** as root
        run: |
          git subtree split -P client -b client-deploy
          git checkout client-deploy
      
      - name: npm install
        run: npm install

      - name: remove yarn.lock
        run: rm -rf yarn.lock
      
      - name: Git add and commit
        run: |
          git add -A
          git commit -m "by github-actions"
          git fetch --all --unshallow

      - name: Add frontend remote origin
        run: git remote add lesson-plans-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME  }}.git
      
      - name: Deploy frontend to Heroku
        run: git push lesson-plans-frontend client-deploy:refs/heads/main --force
